### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Klnsyf-Sun** [tianyilt/ecust-CourseShare#4]
## 比较重要的问题
+ 仓库大小: ![](https://img.shields.io/github/repo-size/tianyilt/ecust-CourseShare.svg)
  - 这是一个**相当不理智**的数值. 尽管理论上Github规定的仓库大小最大不能超过100GB, 但**强烈建议**单个仓库大小**不要超过1GB**, 这会给各部分的流程带来压力.
  - 事实上, 我在文件目录中看到了一些**视频文件**, 它们对于问题的阐释可能是必要的, 但一个**更好的方法**是将它们上传到视频网站上, 留下一个链接即可.
    - 同样的, 文件目录中有大量未经压缩的**图片文件**, 或许可以考虑 @ImgBotApp ?
    - 或者先压缩, 然后打包上传, 这也能一定程度上的缓解问题.
  - 当然, 最重要的是应当**合理筛选**需要上传的文件, 以确保合适的仓库大小.
    - 至少请记得在上传文件时**删除某些系统文件以及图片中的附加信息**, 这也是处于个人信息安全的考量.
+ 版权问题
  - 我在文件目录中看到了相当多的教材(包括但不限于教材主体, 其附属的参考答案, 学习资料等), 这也是仓库大小膨胀的原因之一. 更重要的是, 可能会带来**版权问题**.
    - 某些教材(尤指一些外文教材或其译本), 是受到版权保护的, 其数字版本被禁止公开传递.
        - 这并不能通过README中最后一句: `其他部分的版权归属于其各自的作者` 来回避.
        - 这可能导致本项目被[**Takedown**](https://help.github.com/en/articles/dmca-takedown-policy)
          - 当然由于各种各样的原因, 这并不常见, 但出于各种各样的考虑(笑), 建议尽量回避.
  - 或许单独设立一个**教材归档**的仓库会更为合适. 当然, 我更倾向于这是一个**教材推荐**的Repo或讨论页.
## 一些关于用户体验优化的建议
+ 项目结构
  - 基于目前项目结构比较混乱, 随便扯一点自己的思路.
  - 主分类
    - 该想法基于以下考量:
      - 大多数情况下, 一个用户的操作范围仅限于**公共课程**和其**所属专业课程**. 默认情况下不需要与**其他专业课程**交互, 下载本项目归档文件或Clone时包含所有内容是不合理的.
      - Github**基于分支**生成相应的归档文件
        - 如本项目master分支的归档文件: [:file_folder:ecust-CourseShare-master.zip](https://github.com/tianyilt/ecust-CourseShare/archive/master.zip)
      - Git也可以**Clone单个分支**
        - `$ git clone --branch <name> <repository>`
    - 综上, 提出主分类方案:
      - *master*分支调整为本项目的**docs**.
        - 当然亦可另开一个*docs*分支, 保留*master*为完整合并, 提供给有意图全科目制霸的大佬(笑).
      - 使用**branch**代替一级文件夹进行分类.
        - **每个分支代表一个专业(或公共分类)**.
        - 优点
          - 用户只需要下载或Clone**对应的分支**即可, 而**不是整个项目仓库**.
        - 缺点
          - 这是branch的**错误使用方法**(笑).
          - 略微增加了一点学习成本: 如何切换分支(笑).
  - 目录结构
    - 课程名称\年份\分类\
      - 课程名称: 应当使用**完整准确**的课程名, 建议在名称开头添加首字母, **便于索引**.
      - ..\年份: 考虑到**时效性**, 将其作为一个**优先级较高**的分类, 也有利于日后可能需要的**过时资源归档**.
      - ..\分类: 按照**资源类型**进行分类, 应当有一套**完整**, **全面**, **统一**的分类方案.
        - 还没有想好具体的实现, 或许可以开一个Issue详细讨论一下?
      - ..\\: 底层目录
        - 除底层目录外, 任何父目录**不应**包含任何**除README以外的文件**
        - 文件命名规则: **课程名称-年份-分类-文件名**
          - 便于在**整个项目仓库**中查找特定文件
+ Github Pages
  - 关于本项目的Github Pages, 一般有两个用法:
    - **VISAUL**: 本质上是**单纯的视觉效果**, 提供一个感觉上**更为友好**的界面.
      - 但不得不说Github本身已经较为友好, 而且套一层Github Pages降低加载速度...(笑)
        - 虽然正好可以拿来试试Github Actions(笑).
      - 可以考虑使用[**MkDocs**](https://github.com/mkdocs/mkdocs)等docs框架.
    - **UTIL**: **功能性**的设计, 提供更多的功能.
      - 例如月度总结, 优秀资源PICK UP, 优秀攻略推送之类的.
        - 这一建议出于以下考量:
          - 跟踪项目的**更新情况**较为困难, 尤其是目前**Commit Message**过于含蓄的情况下.
            - 下面还会详细讨论关于**Commit Message**的问题.
          - 突出展示优秀资源, 便于学习, 进而提升整体质量.
      - 当然这就需要有人来写Blog(笑).
      - 可以考虑使用[**hexo**](https://github.com/hexojs/hexo)等blog框架.
## 一些和用户体验无关但和维护体验息息相关的建议
+ Commit规范
  - 虽然这并不是一个一周一回滚一月一重构的项目(笑), 但保持清晰的Commit记录还是有必要的. 适当合并或拆分Commit, 确保每次做完且只做了一件事, 再配上详细完整的Commit Message, 能使记录看起来清爽许多, 也更**便于维护**.
    - 顺便一提, 规范的Commit Message几乎就可以当作是Change Log, 配合Project Boards可以**快速定位需要补全\修正的资源**.
  - 可以考虑使用一道专用的**Commit Template**.
+ 其他
  - 写一个Pull Request Template.
  - 使用一些更好的方式维护Contributors.
    - 比如 @all-contributors ?
  - 关闭暂未使用的功能.
  - **TODO** | ...

**Comment by tianyilt** [comment]
感谢建议，这些将会纳入TODO中

**Comment by tianyilt** [comment]
您好，您的建议非常有价值，为了具体落实有几个方面想进一步咨询您:

1. "单独设立一个教材归档的仓库会更为合适. 当然, 我更倾向于这是一个教材推荐的Repo或讨论页."是一个怎样的形式，是单独开设一个仓库，然后我在这里设置链接吗，教材归档这件事情有模板可以参考吗？

2. “Github基于分支生成相应的归档文件”是指为每一个系的课程单独建立压缩包，然后放在一个单独的分支里面吗，这个归档能否更加灵活，通过压缩包的方式有较多不便。目前我想出来的办法是将带有.git的内容放到百度网盘内，如果没有同步需求的使用者可以直接下载相应文件夹。而开发者可以通过git同步。

3.  我想要这个项目对于刚入学校的没有经验的同学而言，也能方便地找到自己需要的内容，且不必强迫了解git与github相关机制（尽管这非常有必要了解）。这方面我需要一些灵感，目前我希望尽快降低仓库使用门槛。

4. ”关闭暂未使用的功能“是什么意思

5. 目录结构确实需要单开一个issue讨论

**Comment by Klnsyf-Sun** [comment]
#### 1
 **教材归档**的话一个新的仓库或是一个独立的分支都是可行的.
  主要是考虑到在主分支里占的空间比较大, 而且万一出现版权问题需要***revert***主分支太恐怖了.

  至于**教材推荐**的形式可以参考: *https://github.com/TeamStuQ/skill-map*
  与技能图谱类似的, 描述专业学习路径, 推荐合适的教材.
  ***Issues*** 本身就很适合作为讨论区, 也可以通过类似 *Gitalk* 获取更为友好的用户体验.

#### 2 
  首先, 归档文件是由 *Github* 自动生成的.
  比如 *master* 分支会生成在: https://github.com/tianyilt/ecust-CourseShare/archive/master.zip
  这个归档文件会自动更新.

  其次, 这条建议的主要想法是按照不同内容建立不同的分支.
  这其实更多的也是提供 ***Clone*** 的便利性.
  网页端虽然也可以编辑文件, 但每次操作都会作为 *Commit* 提交, 这会导致整个记录混乱.
  最终总是免不了要 *Clone* 项目来获取良好的体验的, 但整个项目太大了.
  而且比如我其实只想修改一下 *README.md*, 但我不得不完整 *Clone* 整个项目.
  实际上其中的学习资料在编辑过程中是不必要的.
  把各种不同的文件放到不同的分支, 我就可以在 *Clone* 时选择唯一的分支.
  操作体验会良好很多.

  大概的效果可以参考我的这个 Repo: https://github.com/Klnsyf-Sun/Klnsyf-s-Utils
  每一个分支都是一个独立的小程序, 这样哪怕中间混了一个3A大作的数据文件(虽然并没有), 其他分支上的同步和编辑体验也不会受到影响.

#### 3
  其实 *Github* 的基本用法还算和谐, *Git* 的基本操作也不是特别难懂, 就是在命令行里敲指令有点劝退.

  基本的下载的话网页版本应该能满足, 或者可以安装一个插件 *GitZip*.
  再不行就只能使用*Github Pages* + *CI\CD* 搞成 ftp 一样的状态了...
  说实话, 安装*GitZip*之后, 下载体验应该已经和大多数网盘类似, 没必要再多搞什么.

  同步只需要了解 *clone* 和 *fetch*, 贡献则还要了解 *fork*, *commit*, *push* 和 *pull request*.
  这些功能的话可以选择使用 *Github Desktop*, 图形化界面的劝退能力应该没有这么强.
  这应该已经是学习成本最低的情况, 否则只能有他人代为操作...

  最近正好在写 *Github Desktop* 的教程, 适当修改后可能会尝试提交一个 *pull request*.

#### 4
  指如果没有计划使用的话, 可以在 *Options* 中关闭部分功能.
  例如决定使用 *README.md* 等一系列文件作为介绍和教程的话, 可以关闭 *Wiki*.

**Comment by tianyilt** [comment]
太感谢了,还有一些其他问题我单开了issue,想请教大佬
