### ISSUE TITLE
来一个 GitHub 项目徽章？

### ISSUE THREAD

**Issue by wuyudi** [tianyilt/ecust-CourseShare#54]
https://lpd-ios.github.io/2017/05/03/GitHub-Badge-Introduction/

**Comment by wuyudi** [comment]
比如项目容量什么的

**Comment by tianyilt** [comment]
好主意,我整活完夏令营看一看

**Comment by tianyilt** [comment]
https://shields.io/category/size
直接进这个网站填上user和rep就完事了,现在就先加了size,其他还没想好
