### ISSUE TITLE
分享方式

### ISSUE THREAD

**Issue by wuyudi** [tianyilt/ecust-CourseShare#55]
https://github.com/TieBaMma/InstallTutorial/issues/33#issuecomment-626136160

这里面有详细的介绍。虽然我现在都是 Telegram 存文件了XD，单文件 2G，无限容量。

**Comment by tianyilt** [comment]
Telegram电报群的问题在于更加需要科学上网了，存储问题目前有两台群辉nas可以解决，缺点是没有实时更新。还有就是在github上pull request，然后再在hub.fastgit.org上进行下载，pull

**Comment by tianyilt** [comment]
找到了nas 同步百度云 百度云同步我本地  我本地同步github的精彩方式,大受震撼,此贴关闭
