### ISSUE TITLE
一直报错

### ISSUE THREAD

**Issue by wuyudi** [tianyilt/ecust-CourseShare#56]
我的邮箱一直收到这个邮件

The page build completed successfully, but returned the following warning for the `master` branch:

It looks like you're using GitHub Pages to distribute binary files. We strongly suggest that you use releases to ship projects on GitHub. Releases are GitHub's way of packaging and providing software to your users. You can think of it as a replacement to using downloads to provide software. We found the following file(s) which may be a good candidate for releases: 信息科学与工程学院/Java程序设计实验/课件和源代码/课件和源代码/java_source/chapter13/WindowsFormsApplication1/WindowsFormsApplication1/bin/Debug/WindowsFormsApplication1.exe, 信息科学与工程学院/Java程序设计实验/课件和源代码/课件和源代码/java_source/chapter13/WindowsFormsApplication1/WindowsFormsApplication1/bin/Debug/WindowsFormsApplication1.vshost.exe, 信息科学与工程学院/Java程序设计实验/课件和源代码/课件和源代码/java_source/chapter13/WindowsFormsApplication1/WindowsFormsApplication1/obj/x86/Debug/WindowsFormsApplication1.exe, 信息科学与工程学院/Java程序设计实验/课件和源代码/课件和源代码/java_source/chapter4/c++/P.exe, 信息科学与工程学院/Java程序设计实验/课件和源代码/课件和源代码/java_source/chapter4/c++/P2.exe, 信息科学与工程学院/Java程序设计实验/课件和源代码/课件和源代码/java_source/chapter4/c++/P3.exe, 信息科学与工程学院/Java程序设计实验/课件和源代码/课件和源代码/java_source/chapter4/c++/test4.exe, 信息科学与工程学院/Java程序设计实验/课件和源代码/课件和源代码/java_source/chapter4/c++/testsize.exe, 数学系/专业选修/大3上_计算机网络/实验报告/实验五/Win32OpenSSL-1_0_2t.exe, and 数学系/专业选修/大3下_投资学/作业/金太阳行情交易软件/new_gxzq_v6.62.exe.

**Comment by tianyilt** [comment]
这是因为当初开了gitpage 他发现没有可以编译的web文件就报错了

**Comment by tianyilt** [comment]
现在我关掉了
