### ISSUE TITLE
关于转移给组织的问题

### ISSUE THREAD

**Issue by tianyilt** [tianyilt/ecust-CourseShare#8]
我将项目提交给组织之后,lfs失效,容量上限只有1G,因为我们项目太大,要购买额外存储

**Comment by Klnsyf-Sun** [comment]
本仓库并没有开启 *Git Large File Storage*.
// 不然 *Clone* 体验也不至于这么差\笑
只有**单个文件**大小**大于100MB**时需要开启 *Git-LFS*.
正常情况下, *Repo* 大小上限为 **100GB** (大于1GB邮件提醒, 大于75GB警告).

**Comment by tianyilt** [comment]
看来很难转移仓库到一个公共的组织下面了

**Comment by wuyudi** [comment]
没试过组织的方法，不过。。。假如一门课一门仓库会好些吗？（不知道是限制整体的容量还是单仓库的）

**Comment by tianyilt** [comment]
@wuyudi 感谢您的好主意,我觉得这是解决`体积问题`比较好的方法
我有计划将整个项目拆散迁移到码云等国内能够快速访问的平台.可惜该项目有严格的1G限制,通过拆散的方式确实能够解决.
目前计划是建立一个导航项目来组织项目的框架与学习资料,如教会同学1分钟使用github下载资料,不过值得注意的是,如果转移平台,原先批量下载方法是依托于github开源项目的,需要再找个替代方案

之前这个项目遇到三个问题
1. 网络问题(在gfw没有倒掉之前只能换到国内平台,但是会遇到问题2),这也是推广与下载的主要难题
2. 体积问题,3G以上的体积严重限制了该项目的转移灵活度,原先用百度网盘解决,现在该方法已经被百度自动标记失效.
3成员问题 原先协作者只能有5人,这是不现实的,目前github开放了限制得以解决,如果转移到组织将会再度面临协作者上限问题.
