### ISSUE TITLE
Appreciation！

### ISSUE THREAD

**Issue by LeonardJoey** [tianyilt/ecust-CourseShare#9]
**感谢前辈分享华理数据结构PPT**，本人考研党，准备了2020的考研，全网搜索没有找到ECUST的专业课资料，万幸在Git上找到您以及分享之资料。本人打算报考贵校的**计算机技术**专业，希望能认识师兄并给予我经验，斯人在这留下Wechat ID：qiaoz426，希望前辈能与我联系，感激不尽！

**Comment by tianyilt** [comment]
您好,这件事情您可以咨询这位同学QQ1459103511,让他来帮您联系计算机系学长吧
