### ISSUE TITLE
关于多个学院课程重合的处理建议

### ISSUE THREAD

**Issue by Liz-Nozomi** [tianyilt/ecust-CourseShare#90]
我校有比较多的学院共享同一门课程，同时同一门课程又有不同学分，可能会对找寻自己的课程造成一些困扰。是否可以通过开课学院，进行重新分类？比如有机、物化等归入化学系，化工原理与化工原理（少学时）等归入化工系这样，公选课也可以按照开课学院来分

**Comment by tianyilt** [comment]
有道理，之前没想到这个，因为数学物理等开课学院和上课学院是一致的。我觉得可以保持公选课文件夹不动，专业课在开课学院内放材料，然后在上课学院内对应目录的readme里面贴个链接就行了，不用放材料了。

**Comment by Liz-Nozomi** [comment]
已经在操作了，建议数天内不要merge新的pr。新的文件目录需要一段时间来审阅和补充内容，敬请期待。反正找资料的便利程度会比现在好一些。

**Comment by tianyilt** [comment]
#93  解决了
